In [3]:
#Dpendencies and setup
import pandas as pd
import numpy as np

# Read in data
oct_2017_1 = pd.read_csv('resources/oct_2017.csv')
oct_2017_2 = pd.read_csv('resources/oct_2017_2.csv')
oct_2017_3 = pd.read_csv('resources/oct_2017_3.csv')
oct_2018_1 = pd.read_csv('resources/oct_2018.csv')
oct_2018_2 = pd.read_csv('resources/oct_2018_2.csv')
oct_2018_3 = pd.read_csv('resources/oct_2018_4.csv')
oct_2019_1 = pd.read_csv('resources/oct_2019.csv')
oct_2019_2 = pd.read_csv('resources/oct_2019_2.csv')
oct_2020_1 = pd.read_csv('resources/oct_2020.csv')
oct_2020_2 = pd.read_csv('resources/oct_2020_2.csv')
oct_2022_1 = pd.read_csv('resources/oct_2022.csv')
oct_2022_2 = pd.read_csv('resources/oct_2022_2.csv')

C:\Users\JaCk-\AppData\Local\Temp\ipykernel_1456\1653471799.py:16: DtypeWarning: Columns (5,7) have mixed types. Specify dtype option on import or set low_memory=False.
  oct_2022_1 = pd.read_csv('resources/oct_2022.csv')

In [17]:
oct_2020_2.dtypes

tripduration                 int64
starttime                   object
stoptime                    object
start station id             int64
start station name          object
start station latitude     float64
start station longitude    float64
end station id               int64
end station name            object
end station latitude       float64
end station longitude      float64
bikeid                       int64
usertype                    object
birth year                   int64
gender                       int64
dtype: object

In [5]:
oct_2022_2.dtypes

ride_id                object
rideable_type          object
started_at             object
ended_at               object
start_station_name     object
start_station_id       object
end_station_name       object
end_station_id         object
start_lat             float64
start_lng             float64
end_lat               float64
end_lng               float64
member_casual          object
dtype: object

In [16]:
#combine df's with the same column names/data types
oct_2017_2020 = pd.concat([oct_2017_1, oct_2017_2, oct_2017_3, oct_2018_1, oct_2018_2, oct_2018_3, oct_2019_1, oct_2019_2, oct_2020_1, oct_2020_2], ignore_index=True)
oct_2017_2020

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,2110,2017-08-01 00:00:00,2017-08-01 00:35:11,470.0,W 20 St & 8 Ave,40.743453,-74.000040,3289.0,W 90 St & Amsterdam Ave,40.790179,-73.972889,20954,Subscriber,1978.0,2
1,160,2017-08-01 00:00:10,2017-08-01 00:02:51,348.0,W Broadway & Spring St,40.724910,-74.001547,151.0,Cleveland Pl & Spring St,40.722104,-73.997249,15164,Subscriber,1978.0,1
2,1644,2017-08-01 00:00:17,2017-08-01 00:27:41,3165.0,Central Park West & W 72 St,40.775794,-73.976206,3320.0,Central Park West & W 100 St,40.793393,-73.963556,17540,Subscriber,1962.0,2
3,323,2017-08-01 00:00:27,2017-08-01 00:05:51,389.0,Broadway & Berry St,40.710446,-73.965251,3073.0,Division Ave & Hooper St,40.706913,-73.954417,18705,Subscriber,1990.0,1
4,109,2017-08-01 00:00:41,2017-08-01 00:02:31,3145.0,E 84 St & Park Ave,40.778627,-73.957721,3147.0,E 85 St & 3 Ave,40.778012,-73.954071,27975,Subscriber,1983.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10716290,270,2020-10-13 15:05:35.0860,2020-10-13 15:10:05.3430,3207.0,Oakland Ave,40.737604,-74.052478,3640.0,Journal Square,40.733670,-74.062500,44744,Subscriber,1963.0,2
10716291,400,2020-10-13 15:09:03.4890,2020-10-13 15:15:43.9750,3209.0,Brunswick St,40.724176,-74.050656,3209.0,Brunswick St,40.724176,-74.050656,45345,Subscriber,1984.0,1
10716292,206,2020-10-13 15:11:34.3500,2020-10-13 15:15:00.5030,3195.0,Sip Ave,40.730897,-74.063913,3194.0,McGinley Square,40.725340,-74.067622,47019,Subscriber,1993.0,1
10716293,216,2020-10-13 15:11:49.1510,2020-10-13 15:15:25.6930,3195.0,Sip Ave,40.730897,-74.063913,3225.0,Baldwin at Montgomery,40.723659,-74.064194,42191,Subscriber,1966.0,1
10716294,418,2020-10-13 15:12:31.7920,2020-10-13 15:19:30.5280,3267.0,Morris Canal,40.712419,-74.038526,3186.0,Grove St PATH,40.719586,-74.043117,47255,Subscriber,1991.0,1

In [28]:
#rename column names in 2022 for columns that have matching data
oct_2022_1.rename(columns={
    'started_at': 'starttime',
    'ended_at': 'stoptime',
    'start_station_name': 'start station name',
    'end_station_name': 'end station name',
    'start_lat': 'start station latitude',
    'start_lng': 'start station longitude',
    'end_lat': 'end station latitude',
    'end_lng': 'end station longitude',
    'start_station_id': 'start station id',
    'end_station_id': 'end station id',
    'member_casual': 'usertype'
}, inplace = True)

oct_2022_2.rename(columns={
    'started_at': 'starttime',
    'ended_at': 'stoptime',
    'start_station_name': 'start station name',
    'end_station_name': 'end station name',
    'start_lat': 'start station latitude',
    'start_lng': 'start station longitude',
    'end_lat': 'end station latitude',
    'end_lng': 'end station longitude',
    'start_station_id': 'start station id',
    'end_station_id': 'end station id',
    'member_casual': 'usertype'
}, inplace = True)

In [26]:
#change values of usertype in 2022 data to match prior iterations
for x in range(len(oct_2022_1)):
    if oct_2022_1.loc[x, 'usertype'] == 'member':
        oct_2022_1.loc[x, 'usertype'] = 'Subscriber'
    elif oct_2022_1.loc[x, 'usertype'] == 'casual':
        oct_2022_1.loc[x, 'usertype'] = 'Customer'

In [27]:
#change values of usertype in 2022 data to match prior iterations
for x in range(len(oct_2022_2)):
    if oct_2022_2.loc[x, 'usertype'] == 'member':
        oct_2022_2.loc[x, 'usertype'] = 'Subscriber'
    elif oct_2022_2.loc[x, 'usertype'] == 'casual':
        oct_2022_2.loc[x, 'usertype'] = 'Customer'
oct_2022_2

,ride_id,rideable_type,starttime,ended_at,start station name,start station id,end station name,end station id,start station latitude,start station longitude,end station latitude,end station longitude,usertype
0,4999883C92EACCB0,classic_bike,2022-09-01 21:05:47,2022-09-01 21:08:07,Jersey & 3rd,JC074,Brunswick St,JC023,40.723332,-74.045953,40.724176,-74.050656,Subscriber
1,CC87E6815E075F6F,classic_bike,2022-09-10 18:09:26,2022-09-10 18:11:48,Jersey & 3rd,JC074,Brunswick St,JC023,40.723225,-74.045679,40.724176,-74.050656,Subscriber
2,B54E7FDDF4C251E6,classic_bike,2022-09-26 21:46:24,2022-09-26 21:56:06,Jersey & 3rd,JC074,Jersey & 3rd,JC074,40.723275,-74.045694,40.723332,-74.045953,Subscriber
3,A19A3DC77A98F6C2,classic_bike,2022-09-08 20:11:41,2022-09-08 22:01:29,Jersey & 3rd,JC074,Jersey & 3rd,JC074,40.723230,-74.045731,40.723332,-74.045953,Subscriber
4,3530E340A0B0E93F,classic_bike,2022-09-08 17:05:38,2022-09-08 17:10:26,Leonard Gordon Park,JC080,Riverview Park,JC057,40.745789,-74.057112,40.744319,-74.043991,Subscriber
...,...,...,...,...,...,...,...,...,...,...,...,...,...
104242,914104109C27B9C8,electric_bike,2022-09-09 21:50:46,2022-09-09 22:02:44,Madison St & 1 St,HB402,Columbus Dr at Exchange Pl,JC106,40.738790,-74.039300,40.716870,-74.032810,Customer
104243,BF8C9DCD3FE530E7,classic_bike,2022-09-18 17:52:19,2022-09-18 18:05:22,Monmouth and 6th,JC075,Bergen Ave & Stegman St,JC108,40.725604,-74.048829,40.706575,-74.086701,Subscriber
104244,F7DCB86572EC4732,electric_bike,2022-09-28 16:46:08,2022-09-28 16:50:46,4 St & Grand St,HB301,Madison St & 10 St,HB503,40.742258,-74.035111,40.749943,-74.035865,Subscriber
104245,A552D06A517E37E4,classic_bike,2022-09-27 11:39:59,2022-09-27 11:43:58,4 St & Grand St,HB301,Madison St & 10 St,HB503,40.742258,-74.035111,40.749943,-74.035865,Subscriber
104246,CDCAE5569A0464EF,classic_bike,2022-09-02 20:55:22,2022-09-02 21:01:41,4 St & Grand St,HB301,Madison St & 10 St,HB503,40.742258,-74.035111,40.749943,-74.035865,Customer

In [31]:
#drop columns that dont match up with old data
oct_2022_1 = oct_2022_1.drop(columns=['ride_id','rideable_type'])
oct_2022_2 = oct_2022_2.drop(columns=['ride_id','rideable_type'])
oct_2022_2

,starttime,stoptime,start station name,start station id,end station name,end station id,start station latitude,start station longitude,end station latitude,end station longitude,usertype
0,2022-09-01 21:05:47,2022-09-01 21:08:07,Jersey & 3rd,JC074,Brunswick St,JC023,40.723332,-74.045953,40.724176,-74.050656,Subscriber
1,2022-09-10 18:09:26,2022-09-10 18:11:48,Jersey & 3rd,JC074,Brunswick St,JC023,40.723225,-74.045679,40.724176,-74.050656,Subscriber
2,2022-09-26 21:46:24,2022-09-26 21:56:06,Jersey & 3rd,JC074,Jersey & 3rd,JC074,40.723275,-74.045694,40.723332,-74.045953,Subscriber
3,2022-09-08 20:11:41,2022-09-08 22:01:29,Jersey & 3rd,JC074,Jersey & 3rd,JC074,40.723230,-74.045731,40.723332,-74.045953,Subscriber
4,2022-09-08 17:05:38,2022-09-08 17:10:26,Leonard Gordon Park,JC080,Riverview Park,JC057,40.745789,-74.057112,40.744319,-74.043991,Subscriber
...,...,...,...,...,...,...,...,...,...,...,...
104242,2022-09-09 21:50:46,2022-09-09 22:02:44,Madison St & 1 St,HB402,Columbus Dr at Exchange Pl,JC106,40.738790,-74.039300,40.716870,-74.032810,Customer
104243,2022-09-18 17:52:19,2022-09-18 18:05:22,Monmouth and 6th,JC075,Bergen Ave & Stegman St,JC108,40.725604,-74.048829,40.706575,-74.086701,Subscriber
104244,2022-09-28 16:46:08,2022-09-28 16:50:46,4 St & Grand St,HB301,Madison St & 10 St,HB503,40.742258,-74.035111,40.749943,-74.035865,Subscriber
104245,2022-09-27 11:39:59,2022-09-27 11:43:58,4 St & Grand St,HB301,Madison St & 10 St,HB503,40.742258,-74.035111,40.749943,-74.035865,Subscriber
104246,2022-09-02 20:55:22,2022-09-02 21:01:41,4 St & Grand St,HB301,Madison St & 10 St,HB503,40.742258,-74.035111,40.749943,-74.035865,Customer

In [33]:
#add in 2022 data
oct_2017_2022 = pd.concat([oct_2017_2020, oct_2022_1, oct_2022_2], ignore_index=True)
oct_2017_2022

,tripduration,starttime,stoptime,start station id,start station name,start station latitude,start station longitude,end station id,end station name,end station latitude,end station longitude,bikeid,usertype,birth year,gender
0,2110.0,2017-08-01 00:00:00,2017-08-01 00:35:11,470.0,W 20 St & 8 Ave,40.743453,-74.000040,3289.0,W 90 St & Amsterdam Ave,40.790179,-73.972889,20954.0,Subscriber,1978.0,2.0
1,160.0,2017-08-01 00:00:10,2017-08-01 00:02:51,348.0,W Broadway & Spring St,40.724910,-74.001547,151.0,Cleveland Pl & Spring St,40.722104,-73.997249,15164.0,Subscriber,1978.0,1.0
2,1644.0,2017-08-01 00:00:17,2017-08-01 00:27:41,3165.0,Central Park West & W 72 St,40.775794,-73.976206,3320.0,Central Park West & W 100 St,40.793393,-73.963556,17540.0,Subscriber,1962.0,2.0
3,323.0,2017-08-01 00:00:27,2017-08-01 00:05:51,389.0,Broadway & Berry St,40.710446,-73.965251,3073.0,Division Ave & Hooper St,40.706913,-73.954417,18705.0,Subscriber,1990.0,1.0
4,109.0,2017-08-01 00:00:41,2017-08-01 00:02:31,3145.0,E 84 St & Park Ave,40.778627,-73.957721,3147.0,E 85 St & 3 Ave,40.778012,-73.954071,27975.0,Subscriber,1983.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14327660,NaN,2022-09-09 21:50:46,2022-09-09 22:02:44,HB402,Madison St & 1 St,40.738790,-74.039300,JC106,Columbus Dr at Exchange Pl,40.716870,-74.032810,NaN,Customer,NaN,NaN
14327661,NaN,2022-09-18 17:52:19,2022-09-18 18:05:22,JC075,Monmouth and 6th,40.725604,-74.048829,JC108,Bergen Ave & Stegman St,40.706575,-74.086701,NaN,Subscriber,NaN,NaN
14327662,NaN,2022-09-28 16:46:08,2022-09-28 16:50:46,HB301,4 St & Grand St,40.742258,-74.035111,HB503,Madison St & 10 St,40.749943,-74.035865,NaN,Subscriber,NaN,NaN
14327663,NaN,2022-09-27 11:39:59,2022-09-27 11:43:58,HB301,4 St & Grand St,40.742258,-74.035111,HB503,Madison St & 10 St,40.749943,-74.035865,NaN,Subscriber,NaN,NaN
14327664,NaN,2022-09-02 20:55:22,2022-09-02 21:01:41,HB301,4 St & Grand St,40.742258,-74.035111,HB503,Madison St & 10 St,40.749943,-74.035865,NaN,Customer,NaN,NaN

In [34]:
#save aggregated data
oct_2017_2022.to_csv('oct_2017_2022.csv')